[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "your-bunny-wrought"
requires-python = ">=3.12"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "yourbunnywrought.VERSION" }

[tool.setuptools.packages.find]
include = ["yourbunnywrought*"]

[tool.black]
line-length = 119

[tool.ruff]
line-length = 119
